### ISSUE TITLE
MakeRMA Java error

### ISSUE THREAD

**Issue by nvpatin** [PacificBiosciences/pb-metagenomics-tools#10]
Hello,

I am running the Taxonomic-Functional-Profiling-Protein snakemake workflow and am encountering an error with the Java heap space. The error in the MakeRMA.ReadCount.log is below(only showing the last part). I know how to manually increase the Java heap space with the -Xmx parameter, but how can I do this within a snakemake workflow? Or do you have other recommendations for resolving this problem?

Thanks,
Nastassia

Binning reads: Initializing...
Initializing binning...
Using 'Interval-Union-LCA' algorithm (100.0 %) for binning: Taxonomy
Using Multi-Gene Best-Hit algorithm for binning: SEED
Using Multi-Gene Best-Hit algorithm for binning: EGGNOG
Using 'Interval-Union-LCA' algorithm (100.0 %) for binning: GTDB
Using Multi-Gene Best-Hit algorithm for binning: EC
Using Multi-Gene Best-Hit algorithm for binning: INTERPRO2GO
Binning reads...
Binning reads: Analyzing alignments
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
        at java.base/java.util.ArrayList.grow(ArrayList.java:237)
        at java.base/java.util.ArrayList.grow(ArrayList.java:244)
        at java.base/java.util.ArrayList.add(ArrayList.java:454)
        at java.base/java.util.ArrayList.add(ArrayList.java:467)
        at megan/megan.algorithms.AssignmentUsingMultiGeneBestHit.computeAcceptedMatches(AssignmentUsingMultiGeneBestHit.java:153)
        at megan/megan.algorithms.AssignmentUsingMultiGeneBestHit.computeId(AssignmentUsingMultiGeneBestHit.java:75)
        at megan/megan.algorithms.DataProcessor.apply(DataProcessor.java:306)
        at megan/megan.core.Document.processReadHits(Document.java:554)
        at megan/megan.rma6.RMA6FromBlastCreator.parseFiles(RMA6FromBlastCreator.java:362)
        at megan/megan.tools.SAM2RMA6.createRMA6FileFromSAM(SAM2RMA6.java:355)
        at megan/megan.tools.SAM2RMA6.run(SAM2RMA6.java:319)
        at megan/megan.tools.SAM2RMA6.main(SAM2RMA6.java:72)

**Comment by dportik** [comment]
Hi Nastassia, 
You should be able to specify the maximum amount of memory the tools can use when you initially install MEGAN. I generally set mine to 100GB. 

If you do not wish to re-install the tools, you could also try the following (from the manual):
```
You can change the maximum amount of memory permitted after installation by editing the file MEGAN.vmoptions that should be contained in the installation directory, as follows: Edit the amount of memory mentioned there to reflect the desired amount, e.g. 8 gigabytes:
-Xmx8G
```

You will also want to use an appropriate number of threads to achieve the desired memory limit you've set, depending on your HPC setup.

Please let me know if this resolves the issue.

**Comment by dportik** [comment]
Great! I will close this issue now.
