### ISSUE TITLE
Fail job due to "[E::sam_parse1] no SQ lines present in the header"

### ISSUE THREAD

**Issue by CaroleBelliardo** [PacificBiosciences/pb-metagenomics-tools#17]
Hello, 

I have had success using your workflow for several jobs but now I try to run it on a concatenated version of my samples. 
I concatenated reads fasta files and assembled the output with hifiasm. Then, I try to run your workflow on my concatenated file and the assembly result but the job fail.

>Building DAG of jobs...
Creating conda environment envs/gtdbtk.yml...
Downloading and installing remote packages.
Environment for envs/gtdbtk.yml created (location: .snakemake/conda/3bf992ccb93153a5e6c19eb7bdcd20fd)
Creating conda environment envs/python.yml...
Downloading and installing remote packages.
Environment for envs/python.yml created (location: .snakemake/conda/2ce7aab9d22cb6320e1c6e2c20bae8fb)
Creating conda environment envs/metabat.yml...
Downloading and installing remote packages.
Environment for envs/metabat.yml created (location: .snakemake/conda/a1a9b991022be75bac95a1a4dfda5f88)
Creating conda environment envs/dastool.yml...
Downloading and installing remote packages.
Environment for envs/dastool.yml created (location: .snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e)
Creating conda environment envs/samtools.yml...
Downloading and installing remote packages.
Environment for envs/samtools.yml created (location: .snakemake/conda/94312dc5162f930b3832e3ca438c19aa)
Creating conda environment envs/checkm.yml...
Downloading and installing remote packages.
Environment for envs/checkm.yml created (location: .snakemake/conda/085531b418efb4b4242b09049a78046a)
Using shell: /bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job                    count    min threads    max threads
BamDepth                   1              1              1
CheckForBins               1              1              1
MakeFullDASinput           1              1              1
MakeLinCircDASinput        1              1              1
MinimapToBam               1              2              2
ParseContigs               1              1              1
PlotCheckM                 1              1              1
PrepBatchFile              1              1              1
RunCheckM                  1              2              2
RunDAStool                 1              2              2
RunGTDBTkIndividual        1              2              2
RunMetabatFull             1              2              2
RunMetabatLinear           1              2              2
SummarizeCheckM            1              1              1
SummarizeResults           1              1              1
SummaryPlots               1              1              1
WriteCircularBins          1              2              2
all                        1              1              1
total                     18              1              2

>Select jobs to execute...

>[Thu Jan  6 13:14:33 2022]
rule MinimapToBam:
    input: inputs/cat.fasta, inputs/cat.contigs.fasta
    output: 2-bam/cat.bam
    log: logs/cat.MinimapToBam.log
    jobid: 9
    benchmark: benchmarks/cat.MinimapToBam.tsv
    wildcards: sample=cat
    threads: 2
    resources: tmpdir=/tmp

>Activating conda environment: /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/94312dc5162f930b3832e3ca438c19aa
>[E::sam_parse1] no SQ lines present in the header
[E::sam_parse1] no SQ lines present in the header
[E::sam_parse1] no SQ lines present in the header
[E::sam_parse1] no SQ lines present in the header
samtools sort: truncated file. Aborting
[E::sam_parse1] no SQ lines present in the header
[Thu Jan  6 13:26:32 2022]
Error in rule MinimapToBam:
    jobid: 9
    output: 2-bam/cat.bam
    log: logs/cat.MinimapToBam.log (check log file(s) for error message)
    conda-env: /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/94312dc5162f930b3832e3ca438c19aa
>    shell:
        minimap2 -a -k 19 -w 10 -I 10G -g 5000 -r 2000 --lj-min-ratio 0.5 -A 2 -B 5 -O 5,56 -E 4,1 -z 400,50 --sam-hit-only -t 2 >inputs/cat.contigs.fasta inputs/cat.fasta 2> logs/cat.MinimapToBam.log | samtools sort -@ 2 -o 2-bam/cat.bam
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

>Shutting down, this might take some time.
>Exiting because a job execution failed. Look above for error message
>Complete log: /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/log/2022-01-06T124101.965345.snakemake.log

and the ./HiFi-MAG-Pipeline_pacbio/logs/cat.MinimapToBam.log is : 

>[M::mm_idx_gen::235.886*1.51] collected minimizers
[M::mm_idx_gen::298.330*1.60] sorted minimizers
[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::298.330*1.60] loaded/built the index for 310026 target sequence(s)
[M::mm_mapopt_update::317.556*1.57] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 0; #seq: 310026
[M::mm_idx_stat::330.429*1.54] distinct minimizers: 1157354072 (75.16% are singletons); average occurrences: 1.572; average spacing: 5.503

Do you have any idea about what I can do to fix it ?

**Comment by dportik** [comment]
@CaroleBelliardo it looks like the files are now very large so minimap is using a multi-part index. This results in no SQ headers in the bam file. You can add `--split-prefix=pre` to the MinimapToBam rule in the snakemake file and it should then work properly. See below for details:

```
    shell:
        "minimap2 -a -k 19 -w 10 -I 10G -g 5000 -r 2000 --lj-min-ratio 0.5 "
        "-A 2 -B 5 -O 5,56 -E 4,1 -z 400,50 --sam-hit-only -t {threads} --split-prefix=pre "    <- added here
        "{input.contigs} {input.reads} 2> {log} | samtools sort -@ {threads} -o {output}"
```

Please let me know if this solves your issue.

**Comment by CaroleBelliardo** [comment]
Thanks for your help, I think it's good now but I'll let you know when the work is finished. The input files are very large, so it may take a while.

**Comment by CaroleBelliardo** [comment]
Hi Dportik,

It's me again...
Thank for your help in the last failed job. The option --split-prefix=pre fixed the error with MinimapToBam execution and the workflow continue. 
But, it failed now at the stage 4 with the following error message: 


>[Wed Jan 12 17:32:05 2022]
rule RunDAStool:
    input: 4-DAStool/cat.full.tsv, 4-DAStool/cat.linear-circ.tsv, inputs/cat.contigs.fasta, 4-DAStool/cat.bincheck.txt
    output: 4-DAStool/cat/cat_DASTool_bins, 4-DAStool/cat.complete.txt
    log: logs/cat.RunDAStool.log
    jobid: 5
    benchmark: benchmarks/cat.RunDAStool.tsv
    wildcards: sample=cat
    threads: 2
    resources: tmpdir=/tmp

Activating conda environment: /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e
[Thu Jan 13 10:18:58 2022]
Error in rule RunDAStool:
    jobid: 5
    output: 4-DAStool/cat/cat_DASTool_bins, 4-DAStool/cat.complete.txt
    log: logs/cat.RunDAStool.log (check log file(s) for error message)
    conda-env: /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e
    shell:
        DAS_Tool -i 4-DAStool/cat.linear-circ.tsv,4-DAStool/cat.full.tsv -c inputs/cat.contigs.fasta -l lincirc,full -o 4-DAStool/cat/cat --search_engine diamond --write_bins 1 -t 2 --score_threshold 0.2 --debug &> logs/cat.RunDAStool.log && touch 4-DAStool/cat.complete.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

And, the log file 'logs/cat.RunDAStool.log' contain : 

>Running DAS Tool using 2 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 2.0.13
/lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:793:in `flock': Bad file descriptor @ rb_file_flock - /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/gems/3.1.0/specifications/default/abbrev-0.1.0.gemspec (Errno::EBADF)
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:793:in `block in open_with_flock'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:790:in `open'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:790:in `open_with_flock'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:1119:in `load'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:800:in `block in each_spec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:772:in `block (2 levels) in each_gemspec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:771:in `each'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:771:in `block in each_gemspec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:770:in `each'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:770:in `each_gemspec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:799:in `each_spec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:870:in `load_defaults'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:1353:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
mv: cannot stat '4-DAStool/cat/cat_proteins.faa.scg': No such file or directory
/lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:793:in `flock': Bad file descriptor @ rb_file_flock - /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/gems/3.1.0/specifications/default/abbrev-0.1.0.gemspec (Errno::EBADF)
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:793:in `block in open_with_flock'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:790:in `open'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:790:in `open_with_flock'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:1119:in `load'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:800:in `block in each_spec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:772:in `block (2 levels) in each_gemspec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:771:in `each'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:771:in `block in each_gemspec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:770:in `each'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:770:in `each_gemspec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:799:in `each_spec'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems/specification.rb:870:in `load_defaults'
	from /lerins/hub/projects/25_IPN_Metag/HiFi-MAG-Pipeline_pacbio/HiFi-MAG-Pipeline_hifiasm3_cat_2/.snakemake/conda/2f9793daeb6f2dac1d12256149d0ce1e/lib/ruby/3.1.0/rubygems.rb:1353:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
mv: cannot stat '4-DAStool/cat/cat_proteins.faa.scg': No such file or directory
rm: cannot remove '4-DAStool/cat/cat_proteins.faa.findSCG.b6': No such file or directory
rm: cannot remove '4-DAStool/cat/cat_proteins.faa.scg.candidates.faa': No such file or directory
rm: cannot remove '4-DAStool/cat/cat_proteins.faa.all.b6': No such file or directory
single copy gene prediction using diamond failed. Aborting

Do you have some advice to fix this new issues. Thank again for your help...

**Comment by dportik** [comment]
@CaroleBelliardo I am not sure what the specific issue is here. It looks like the diamond search failed, but it is not clear why.

Would you be able to paste the contents of `logs/cat.CheckForBins.log`? This can tell us if there were actually bins produced by Metabat2, which are required for DAS_Tool.

**Comment by CaroleBelliardo** [comment]
Hello dear dportik,

the contents of the file logs/cat.CheckForBins.log  is :
---

Bins were found for both binning strategies.

-

I really not understand what happen...

**Comment by dportik** [comment]
Hi @CaroleBelliardo,
Well that checks one thing off of the list of possibilities.

Something I also noticed is that `Running DAS Tool using 2 threads.` was in your log file. This will almost certainly cause a memory issue with DIAMOND. The default in the config file was 24, and you may need to go higher than that (48 or 60). I am assuming the fasta file here is the concatenated one, so it will be much larger in size than your previous runs. I would try this next to see if you can finish the DAS_Tool step.

**Comment by CaroleBelliardo** [comment]
Hello, 
thanks for your answer. I don't understand because I use 70 threads in my config file : 
"

# Choose the assembler used to generate the contigs. Choices currently include:
# hicanu 
# hifiasm-meta
# metaflye

# If you select metaflye, you must also provide the SAMPLE-assembly_info.txt file
# for each sample in the inputs/ folder. 

# The choice of assembler changes how the script will look for circular contigs in the 
# contigs fasta files. This step is important in separating the circular and linear contigs 
# into different files, as binning is only performing for the linear contigs.
assembler: "hifiasm-meta"


# The path to use as the temporary directory to write large files to, which is used with the
# --tmpdir flag in checkm, and the --scratch_dir flag in gtdb. If using HPC, use "/scratch" 
# if you have access. If you do not have access to "/scratch" on HPC or are running 
# snakemake locally, change to a valid directory.
tmpdir: "/lerins/hub/tmp"


minimap:
  # The number of threads to use for minimap2.
  threads: 70
  
metabat:
  # The number of threads to use for metabat2.
  threads: 70

dastool:
  # The number of threads to use for DAS Tool.
  threads: 70
  # The engine for single copy gene searching, choices include:
  # blast, diamond, usearch.
  search: "blast"
  # Score threshold until selection algorithm will keep selecting bins [0 to 1].
  # This is roughly equivalent to CheckM completeness score (0.2 = 20% completeness).
  # If the desired minimum completeness is changed in the gtdbtk section below, 
  # ensure this value is lower or DAS_Tool will remove the bins. The default is to set 
  # DAS_Tool score to 0.2 (20%), and later filter out all bins with <70% completeness. 
  score_threshold: 0.2
  
checkm:
  # The number of threads to use for CheckM.
  threads: 70
  
  # The number of threads to use for pplacer when it is called within checkm.
  pplacer_threads: 70
  
  # A full path to the data downloaded from: https://data.ace.uq.edu.au/public/CheckM_databases/
  # The resulting file must be decompressed to use it.
  # This path is used for the "checkm data setRoot <checkm_data_dir>" command.
  # The path below must point to the directory that contains the following folders:
  # distributions, genome_tree, hmms, hmms_ssu, img, pfam, test_data, and the two tsv files.
  datapath: "/lerins/hub/DB/CheckM"
  
  
gtdbtk:
  # The minimum percent completeness for a genome bin.
  min_completeness: 50
  
  # The maximum percent contamination for a genome bin.
  max_contamination: 10
  
  # The maximum number of contigs allowed in a genome bin.
  max_contigs: 100
  
  # The number of threads to use for gtdb-tk.
  threads: 70
  
  # The number of threads to use for pplacer when it is called within gtdbtk.
  pplacer_threads: 70
  
  # The path the database downloaded for gtdbtk.
  # To download the latest release you can use:
  # wget https://data.gtdb.ecogenomic.org/releases/latest/auxillary_files/gtdbtk_data.tar.gz
  # tar -xvzf gtdbtk_data.tar.gz  
  # Please note that the data for release 202 are ~50GB in size.
  # The path below must point to the directory than contains the following folders:
  # fastani, markers, masks, metadata, mrca_red, msa, pplacer, radii, taxonomy
  gtdbtk_data: "/lerins/hub/DB/GTDB/release20211115"
"
Were can I change this number of threads, if it's not in the file config.yalm ?

**Comment by dportik** [comment]
@CaroleBelliardo Either the `config.yaml` in your snakemake directory is not this one, or you ran the job on a node that did not have 70 threads available and it automatically reduced it to 2 threads instead. I strongly suspect you are using the wrong config file because in the log you sent DAS_Tool was using diamond (the default), not blast (as indicated in this config file). 

FYI, you do not want to use 70 threads for pplacer, use the recommended number (24 or less) or you will likely experience memory overflow issues.

**Comment by dportik** [comment]
@CaroleBelliardo any update on this issue?
