### ISSUE TITLE
HiFi-MAG-Pipeline: Error in rule PlotCheckM

### ISSUE THREAD

**Issue by kkowalden** [PacificBiosciences/pb-metagenomics-tools#22]
Hello,

I am running the HiFi-MAG-Pipeline on our cluster with the following command.

```
snakemake --snakefile Snakefile-hifimags \
--configfile configs/Sample-Config.yaml \
--use-conda \
--cluster "sbatch \
--partition=hpcbio \
--cpus-per-task={threads}" \
-j 2 \
--jobname "{rule}.{wildcards}.{jobid}" \
--latency-wait 60
```

Output is produced as expected until step 8, when following error is thrown.

```
Error in rule PlotCheckM:
    jobid: 15
    output: 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-unfiltered-compl-vs-contam.pdf, 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-unfiltered-compl-vs-contam-contigNums.pdf, 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-unfiltered-compl-vs-contam-Bins.pdf, 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-filtered-compl-vs-contam.pdf, 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-filtered-compl-vs-contam-contigNums.pdf, 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-filtered-compl-vs-contam-Bins.pdf
    log: logs/Sample77_metahifiasm_pctg.PlotCheckM.log (check log file(s) for error message)
    conda-env: /home/groups/hpcbio/pipeline/pb-metagenomics-tools/HiFi-MAG-Pipeline/.snakemake/conda/47890e162aa744cdee3ca81dd478d137
    shell:
        python scripts/Metabat-Plot.py -i 6-checkm-summary/CheckM.Sample77_metahifiasm_pctg.qa.txt -l Sample77_metahifiasm_pctg -c 70 -m 10 -g 20 -o1 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-unfiltered-compl-vs-contam.pdf -o2 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-unfiltered-compl-vs-contam-contigNums.pdf -o3 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-unfiltered-compl-vs-contam-Bins.pdf -o4 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-filtered-compl-vs-contam.pdf -o5 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-filtered-compl-vs-contam-contigNums.pdf -o6 8-summary/Sample77_metahifiasm_pctg/Sample77_metahifiasm_pctg-binplots/Sample77_metahifiasm_pctg-filtered-compl-vs-contam-Bins.pdf &> logs/Sample77_metahifiasm_pctg.PlotCheckM.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

I suspect the error is from sns.jointplot called in scripts/Metabat-Plot.py as the PlotCheckM.log has:

```
Traceback (most recent call last):
  File "scripts/Metabat-Plot.py", line 130, in <module>
    main()
  File "scripts/Metabat-Plot.py", line 122, in main
    create_unfiltered_joint_scatter(df, args.output1)
  File "scripts/Metabat-Plot.py", line 56, in create_unfiltered_joint_scatter
    sns.jointplot(df['Completeness'], df['Contamination'], s=50, alpha=0.7, xlim=(68,102), ylim=(-0.5,10.5))
TypeError: jointplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given
```

I'm not sure if this is something specific to our environment or a bug.
Any advice is appreciated.

Kim

**Comment by dportik** [comment]
Hi @kkowalden,
Thanks for your patience - I've been traveling a bunch for conferences and just returned.

This looks like an issue related to seaborn v0.11 -> 0.12 breaking the jointplot syntax.

I went ahead and updated the `Metabat-Plot.py` script in the `scripts` folder. Please replace yours with the new version of `Metabat-Plot.py`and let me know if the issue persists.

**Comment by kkowalden** [comment]
Great, thanks! It looks like the final summary files have been correctly produced.
I'll let you know if there are any further issues.

Kim

**Comment by dportik** [comment]
Thanks for letting me know! If anything else comes up, please open a new issue.

**Comment by ye00ye** [comment]
i met the same problem, but i cann't find new verison of Metabat-Plot.py, could you please give me the file. thanks

**Comment by dportik** [comment]
Hi @ye00ye ,
Download release [v1.6.1 ](https://github.com/PacificBiosciences/pb-metagenomics-tools/releases/tag/v1.6.1).

However, please be aware that there is a new version of the HiFi-MAG-Pipeline (v2.0) and I strongly recommend using this instead. It produces superior results, please see the list of improvements and benchmarking [here](https://github.com/PacificBiosciences/pb-metagenomics-tools/blob/master/docs/Tutorial-HiFi-MAG-Pipeline.md).
