### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'cbc'

### ISSUE THREAD

**Issue by dgg32** [PacificBiosciences/pb-metagenomics-tools#3]
Hi I am trying to run this workflow on my project. However, I have encountered the following error:

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 48
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	BamDepth
	1	FullBatchFile
	1	MinimapToBam
	1	PlotCheckM
	1	PrepBatchFile
	1	RunCheckM
	1	RunGTDBTkFull
	1	RunGTDBTkIndividual
	1	RunMetabat
	1	SummarizeCheckM
	1	SummarizeResults
	1	all
	12
Traceback (most recent call last):
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/site-packages/snakemake/__init__.py", line 743, in snakemake
    keepincomplete=keep_incomplete,
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/site-packages/snakemake/workflow.py", line 977, in execute
    success = scheduler.schedule()
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/site-packages/snakemake/scheduler.py", line 425, in schedule
    run = self.job_selector(needrun)
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/site-packages/snakemake/scheduler.py", line 662, in job_selector_ilp
    prob.solve(solver)
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/site-packages/pulp/pulp.py", line 1890, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/site-packages/pulp/apis/coin_api.py", line 101, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/site-packages/pulp/apis/coin_api.py", line 152, in solve_CBC
    cbc = subprocess.Popen(args, stdout = pipe, stderr = pipe, stdin=devnull)
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/opt/hpcopt/sixing/anaconda3/envs/pb-binning/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'cbc'.

My snakemake is 5.26.1.

**Comment by dportik** [comment]
This is a duplicate issue that has been addressed [here](https://github.com/PacificBiosciences/pb-metagenomics-tools/issues/2). Only difference was the version of snakemake that was run.

**Comment by dgg32** [comment]
Hi. Today when I tried to rerun the updated submission, the error still came up. But it appeared that the user need to install coincbc first:

`conda install -c conda-forge coincbc`

**Comment by dportik** [comment]
The `PermissionError: [Errno 13]` seems to be related to whether or not you have permission to read/write to a location. 

Snakemake should handle dependencies automatically. Have you been running the newest version of snakemake with the genome-binning-pipeline environment created when you ran 5.3.0? This can also potentially cause conflicts.
