### ISSUE TITLE
UpdateNCBI.prot error

### ISSUE THREAD

**Issue by minjaeyu719** [PacificBiosciences/pb-metagenomics-tools#59]
I got the following error using pb-metagenomics-tools. I tried temporarily disabling the firewall and changing the nameserver address, but it didn't work, so I'm asking this question.

Error in rule UpdateNCBI:
    jobid: 26
    input: /home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/6-c2c/SAMPLE.NCBI.counts.unfiltered.txt
    output: /home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/7-kraken-mpa-reports/NCBI-updated.txt, /home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/taxdump.tar.gz
    log: /home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/logs/UpdateNCBI.prot.log (check log file(s) for error details)
    conda-env: /home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/.snakemake/conda/cd4dc0916fa12c1127259b6c2ddf2b4b_
    shell:
        python scripts/Run_ete3_NCBI_update.py -i /home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/6-c2c/SAMPLE.NCBI.counts.unfiltered.txt -o /home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/7-kraken-mpa-reports/NCBI-updated.txt &> /home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/logs/UpdateNCBI.prot.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by minjaeyu719** [comment]
Uploading to /home/kdy/.etetoolkit/taxa.sqlite

Traceback (most recent call last):
  File "scripts/Run_ete3_NCBI_update.py", line 41, in <module>
    main()
  File "scripts/Run_ete3_NCBI_update.py", line 35, in main
    ncbi = activate_ncbi()
  File "scripts/Run_ete3_NCBI_update.py", line 27, in activate_ncbi
    ncbi = NCBITaxa()
  File "/home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/.snakemake/conda/cd4dc0916fa12c1127259b6c2ddf2b4b_/lib/python2.7/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 110, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/.snakemake/conda/cd4dc0916fa12c1127259b6c2ddf2b4b_/lib/python2.7/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 129, in update_taxonomy_database
    update_db(self.dbfile)
  File "/home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/.snakemake/conda/cd4dc0916fa12c1127259b6c2ddf2b4b_/lib/python2.7/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 760, in update_db
    upload_data(dbfile)
  File "/home/kdy/Han_Lab/10.Yu_Minjae/pb-metagenomics-tools-2.0.0/Taxonomic-Profiling-Diamond-Megan/.snakemake/conda/cd4dc0916fa12c1127259b6c2ddf2b4b_/lib/python2.7/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 802, in upload_data
    db.execute("INSERT INTO synonym (taxid, spname) VALUES (?, ?);", (taxid, spname))
sqlite3.IntegrityError: UNIQUE constraint failed: synonym.spname, synonym.taxid

additional errors

**Comment by dportik** [comment]
Hi @minjaeyu719 ,

As this is a bug report, please use the `bug report` issue template next time. It will help us understand the problem and solve it quicker.

This seems to be an issue with the `ete3` package, which I do not maintain. My recommendation is to try using the newest version, which appears to have been release last month (and which addresses several problems).

To do this, edit the `envs/general.yml` file:
```
name: general_env
channels:
- bioconda
- conda-forge
- defaults
dependencies:
- exonerate == 2.4.0
- diamond >= 2.0.8
- python == 3.7
- pandas
- numpy
- biopython
- ete3 == 3.1.2 ****CHANGE THIS TO 3.1.3
```

It should install a new environment with this latest version. Try that and see if the issue persists.

**Comment by dportik** [comment]
Hi @minjaeyu719 ,
Do you have any updates on this issue? Did you try changing the environment file?

**Comment by minjaeyu719** [comment]
Thanks to your help, I was able to work it out.
Thanks again.
